packages:
  - .

overrides:
  '@preact/signals-core': 1.14.3
  caniuse-lite: 1.0.30001802
  electron-to-chromium: 1.5.386

allowBuilds:
  '@sentry/cli': false
  esbuild: true
  sharp: true
  unrs-resolver: true
