import {
  BORDER_STEPS,
  COLOR_STEPS,
  CW,
  cubicBezier,
  FONT_ROLES,
  type Mode,
  NEUTRAL_STEPS,
  RADIUS_STEPS,
  SHADOW_STEPS,
  SPACE_STEPS,
  STATUSES,
  STROKE,
  TAP_MIN,
  TEXT_STEPS,
  WEIGHTS,
} from './cw'

const HEADER = `/*
 * Generated by \`pnpm generate:theme\` from src/lib/theme/cw.ts: edit cw.ts
 * and rerun, never this file (the int test cw-tokens fails on a hand edit).
 * cw's primitives, named as in gui/themes/cw.md. A value that differs between
 * the modes is written once as light-dark(<light>, <dark>), which follows the
 * color-scheme of the surface using it. The names that aren't cw's are
 * --tap-min, critwire's tap-target floor (D10), and --stroke-s/--stroke-l,
 * its stroke widths (cc-site D7). The roles are in
 * src/styles/cw.css.
 */
`

const px = (value: number) => `${value}px`

/** One value per mode, written once when both modes agree. */
const perMode = (value: (mode: Mode) => string) => {
  const light = value('light')
  const dark = value('dark')
  return light === dark ? light : `light-dark(${light}, ${dark})`
}

/** A neutral step at an opacity, as the snapshot writes shadow colours. */
const shadowColor = (mode: Mode, step: (typeof NEUTRAL_STEPS)[number], opacity: number) =>
  `${CW[mode].neutral[step]}${Math.round(opacity * 255)
    .toString(16)
    .padStart(2, '0')}`

const declarations = (): [string, string][] => [
  ...SPACE_STEPS.map((step): [string, string] => [`--space-${step}`, px(CW.space[step])]),
  ...TEXT_STEPS.flatMap((step): [string, string][] => [
    [`--size-${step}`, px(CW.text[step].size)],
    [`--line-${step}`, px(CW.text[step].lineHeight)],
    [`--letter-spacing-${step}`, `${CW.text[step].letterSpacing}em`],
  ]),
  ...RADIUS_STEPS.map((step): [string, string] => [`--radius-${step}`, px(CW.radius[step])]),
  ...BORDER_STEPS.map((step): [string, string] => [`--border-${step}`, px(CW.border[step])]),
  ...FONT_ROLES.flatMap((role): [string, string][] => [
    [`--font-${role}-fallback`, CW.fonts[role].fallback.join(', ')],
    ...WEIGHTS.map((weight): [string, string] => [`--weight-${role}-${weight}`, String(CW.fonts[role].weights[weight])]),
  ]),
  ['--shadow-none', 'none'],
  ...SHADOW_STEPS.map((step): [string, string] => {
    const { x, y, blur, spread, opacity, color } = CW.shadow[step]
    return [
      `--shadow-${step}`,
      perMode((mode) => `${[x, y, blur, spread].map(px).join(' ')} ${shadowColor(mode, color[mode], opacity)}`),
    ]
  }),
  ['--motion-duration', `${CW.motion.small.duration}ms`],
  ['--motion-easing', cubicBezier(CW.motion.small.easing)],
  ['--motion-large-duration', `${CW.motion.large.duration}ms`],
  ['--motion-large-easing', cubicBezier(CW.motion.large.easing)],
  ['--motion-popup-scale', String(CW.motion.popupScale)],
  ['--motion-press-distance', px(CW.motion.pressDistance)],
  ['--focus-ring-width', px(CW.focus.width)],
  ['--focus-ring-offset', px(CW.focus.offset)],
  ['--focus-ring-mix', `${CW.focus.mix}%`],
  ['--icon-stroke-width', String(CW.iconStrokeWidth)],
  ['--tap-min', px(TAP_MIN)],
  ['--stroke-s', px(STROKE.s)],
  ['--stroke-l', px(STROKE.l)],
  ...COLOR_STEPS.map((step): [string, string] => [`--color-${step}`, CW.color[step]]),
  ...STATUSES.map((status): [string, string] => [`--${status}`, CW.status[status]]),
  ['--accent-text', perMode((mode) => CW[mode].accentText)],
  ...NEUTRAL_STEPS.map((step): [string, string] => [`--neutral-${step}`, perMode((mode) => CW[mode].neutral[step])]),
]

/** The whole of `src/styles/cw-tokens.css`. */
export const cwTokensCSS = (): string =>
  `${HEADER}:root {\n${declarations()
    .map(([name, value]) => `  ${name}: ${value};\n`)
    .join('')}}\n`
