import {
  BORDER_STEPS,
  COLOR_STEPS,
  cubicBezier,
  FOCUS,
  FONT_ROLES,
  type Mode,
  NEUTRAL_STEPS,
  RADIUS_STEPS,
  SHADOW_STEPS,
  SPACE_STEPS,
  STATUSES,
  STROKE,
  TAP_MIN,
  TEXT_STEPS,
  TOKENS,
  WEIGHTS,
} from './tokens'

const HEADER = `/*
 * Generated by \`pnpm generate:theme\` from src/lib/theme/tokens.ts: edit
 * tokens.ts and rerun, never this file (the int test theme-tokens fails on a
 * hand edit). The theme's primitives, named as in gui/themes/cc.md. A value
 * that differs between the modes is written twice: its light value for every
 * browser, then light-dark(<light>, <dark>) where light-dark() is supported,
 * which follows the color-scheme of the surface using it (D3). The names that
 * aren't the theme's are --tap-min, critwire's tap-target floor (D10),
 * --stroke-s/--stroke-l, its stroke widths (D7), and the focus ring's
 * geometry (A5). The roles are in src/styles/roles.css.
 */
`

const SUPPORTS = '@supports (color: light-dark(white, black))'

const px = (value: number) => `${value}px`

type Declaration = [name: string, value: string | Record<Mode, string>]

/** One value per mode, kept as one when both modes agree. */
const perMode = (value: (mode: Mode) => string): string | Record<Mode, string> => {
  const light = value('light')
  const dark = value('dark')
  return light === dark ? light : { light, dark }
}

const declarations = (): Declaration[] => [
  ...SPACE_STEPS.map((step): Declaration => [`--space-${step}`, px(TOKENS.space[step])]),
  ...TEXT_STEPS.flatMap((step): Declaration[] => [
    [`--size-${step}`, px(TOKENS.text[step].size)],
    [`--line-${step}`, px(TOKENS.text[step].lineHeight)],
    [`--letter-spacing-${step}`, `${TOKENS.text[step].letterSpacing}em`],
  ]),
  ...RADIUS_STEPS.map((step): Declaration => [`--radius-${step}`, px(TOKENS.radius[step])]),
  ...BORDER_STEPS.map((step): Declaration => [`--border-${step}`, px(TOKENS.border[step])]),
  ...FONT_ROLES.flatMap((role): Declaration[] => [
    [`--font-${role}-fallback`, TOKENS.fonts[role].fallback.join(', ')],
    ...WEIGHTS.map((weight): Declaration => [`--weight-${role}-${weight}`, String(TOKENS.fonts[role].weights[weight])]),
  ]),
  ['--shadow-none', 'none'],
  ...SHADOW_STEPS.map((step): Declaration => [`--shadow-${step}`, TOKENS.shadow[step]]),
  ['--motion-duration', `${TOKENS.motion.small.duration}ms`],
  ['--motion-easing', cubicBezier(TOKENS.motion.small.easing)],
  ['--motion-large-duration', `${TOKENS.motion.large.duration}ms`],
  ['--motion-large-easing', cubicBezier(TOKENS.motion.large.easing)],
  ['--motion-popup-scale', String(TOKENS.motion.popupScale)],
  ['--motion-press-distance', px(TOKENS.motion.pressDistance)],
  ['--focus-ring-width', px(FOCUS.width)],
  ['--focus-ring-offset', px(FOCUS.offset)],
  ['--icon-stroke-width', String(TOKENS.iconStrokeWidth)],
  ['--tap-min', px(TAP_MIN)],
  ['--stroke-s', px(STROKE.s)],
  ['--stroke-l', px(STROKE.l)],
  ...COLOR_STEPS.map((step): Declaration => [`--color-${step}`, TOKENS.color[step]]),
  ...STATUSES.map((status): Declaration => [`--${status}`, TOKENS.status[status]]),
  ['--accent-text', perMode((mode) => TOKENS[mode].accentText)],
  ...NEUTRAL_STEPS.map((step): Declaration => [`--neutral-${step}`, perMode((mode) => TOKENS[mode].neutral[step])]),
]

const lines = (entries: [string, string][], indent: string) =>
  entries.map(([name, value]) => `${indent}${name}: ${value};\n`).join('')

/** The whole of `src/styles/tokens.css`. */
export const tokensCSS = (): string => {
  const all = declarations()
  const light = all.map(([name, value]): [string, string] => [name, typeof value === 'string' ? value : value.light])
  const pairs = all.flatMap(([name, value]): [string, string][] =>
    typeof value === 'string' ? [] : [[name, `light-dark(${value.light}, ${value.dark})`]],
  )
  return `${HEADER}:root {\n${lines(light, '  ')}}\n\n${SUPPORTS} {\n  :root {\n${lines(pairs, '    ')}  }\n}\n`
}
