/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    'game-projects': GameProject;
    'patch-notes': PatchNote;
    issues: Issue;
    'issue-reports': IssueReport;
    'issue-votes': IssueVote;
    pages: Page;
    media: Media;
    users: User;
    'abuse-reports': AbuseReport;
    'discord-posts': DiscordPost;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'game-projects': GameProjectsSelect<false> | GameProjectsSelect<true>;
    'patch-notes': PatchNotesSelect<false> | PatchNotesSelect<true>;
    issues: IssuesSelect<false> | IssuesSelect<true>;
    'issue-reports': IssueReportsSelect<false> | IssueReportsSelect<true>;
    'issue-votes': IssueVotesSelect<false> | IssueVotesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'abuse-reports': AbuseReportsSelect<false> | AbuseReportsSelect<true>;
    'discord-posts': DiscordPostsSelect<false> | DiscordPostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'email-contact-form': TaskEmailContactForm;
      'discord-webhook': TaskDiscordWebhook;
      'discord-update-post': TaskDiscordUpdatePost;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Used in URLs. Lowercase letters, numbers, and hyphens only.
   */
  slug: string;
  /**
   * Hides the studio's portals and blocks its members' changes.
   */
  suspended?: boolean | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles: ('admin' | 'user')[];
  tenants?:
    | {
        tenant: number | Tenant;
        roles: ('owner' | 'member')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-projects".
 */
export interface GameProject {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * One line under the name on your portal and in link previews.
   */
  description?: string | null;
  logo?: (number | null) | Media;
  banner?: (number | null) | Media;
  /**
   * Match your portal to your own site. Colours are checked for readable (WCAG) contrast when you save.
   */
  theme?: {
    /**
     * 6-digit hex colours, like #22d3ee.
     */
    colors?: {
      background?: string | null;
      foreground?: string | null;
      mutedForeground?: string | null;
      surface?: string | null;
      accent?: string | null;
      accentForeground?: string | null;
      border?: string | null;
      success?: string | null;
      warning?: string | null;
      error?: string | null;
    };
    typography?: ('modern' | 'editorial' | 'technical') | null;
    shape?: ('sharp' | 'balanced' | 'soft') | null;
    density?: ('compact' | 'cinematic') | null;
    motion?: ('off' | 'subtle') | null;
  };
  /**
   * External links shown on the public portal.
   */
  links?: {
    website?: string | null;
    steam?: string | null;
    epic?: string | null;
    itch?: string | null;
    discord?: string | null;
    support?: string | null;
    docs?: string | null;
    merch?: string | null;
    playstation?: string | null;
    xbox?: string | null;
    nintendo?: string | null;
    gog?: string | null;
    youtube?: string | null;
    pressKit?: string | null;
    privacy?: string | null;
    terms?: string | null;
  };
  /**
   * Release and platform facts shown on the public portal.
   */
  availability?: {
    releaseState?: ('comingSoon' | 'earlyAccess' | 'released' | 'freeToPlay') | null;
    releaseDate?: string | null;
    /**
     * e.g. v1.2.0
     */
    currentVersion?: string | null;
    platforms?:
      | {
          platform:
            'windows' | 'mac' | 'linux' | 'steamDeck' | 'playstation' | 'xbox' | 'switch' | 'ios' | 'android' | 'web';
          storeUrl?: string | null;
          /**
           * Optional availability note, e.g. "Demo available".
           */
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Where public contact form submissions are routed.
   */
  contact?: {
    target?: ('EMAIL' | 'DISCORD_WEBHOOK' | 'EXTERNAL_URL' | 'TALLY') | null;
    email?: string | null;
    discordWebhookUrl?: string | null;
    externalUrl?: string | null;
    /**
     * Tally share URL (https://tally.so/r/…) or form ID. Submissions stay in Tally.
     */
    tallyUrl?: string | null;
    tallyDisplay?: ('embed' | 'button') | null;
  };
  /**
   * How players send bug reports and ideas. Prefer Tally so submissions and spam handling stay on their free tier.
   */
  reportForm?: {
    provider?: ('native' | 'tally' | 'external') | null;
    /**
     * Tally share URL or form ID. Submissions are managed in Tally, not Critwire.
     */
    tallyUrl?: string | null;
    tallyDisplay?: ('embed' | 'button') | null;
    /**
     * GitHub issue template, Linear form, Discord channel invite, etc.
     */
    externalUrl?: string | null;
    /**
     * Players can suggest ideas as well as report bugs.
     */
    acceptIdeas?: boolean | null;
    /**
     * When off, clean submissions publish at once. Submissions the content filter flags always wait for review, and turning this off does not publish submissions already waiting.
     */
    reviewSubmissions?: boolean | null;
  };
  /**
   * Custom domain (Phase 8). Verification required before it serves traffic.
   */
  customDomain?: string | null;
  customDomainVerified?: boolean | null;
  /**
   * Managed from the Share tab.
   */
  discord?: {
    guildId?: string | null;
    channelId?: string | null;
    webhookUrl?: string | null;
  };
  /**
   * Held for review: not public until a Critwire admin approves it.
   */
  flagged?: boolean | null;
  flagReasons?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patch-notes".
 */
export interface PatchNote {
  id: number;
  tenant?: (number | null) | Tenant;
  gameProject: number | GameProject;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * e.g. v1.2.0, Hotfix 3
   */
  versionLabel?: string | null;
  /**
   * Short teaser shown in the updates feed.
   */
  summary?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt?: string | null;
  /**
   * Held for review: not public until a Critwire admin approves it.
   */
  flagged?: boolean | null;
  flagReasons?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issues".
 */
export interface Issue {
  id: number;
  _order?: string | null;
  tenant?: (number | null) | Tenant;
  gameProject: number | GameProject;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  summary?: string | null;
  details?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  type: 'BUG' | 'IDEA';
  category:
    | 'INFORMATION'
    | 'PATCH_NOTES'
    | 'GAMEPLAY'
    | 'CRASHES'
    | 'USER_INTERFACE'
    | 'AUDIO'
    | 'VISUAL'
    | 'QUESTS'
    | 'PERFORMANCE'
    | 'OTHER';
  status:
    | 'REPORTED'
    | 'INVESTIGATING'
    | 'NEEDS_MORE_INFO'
    | 'WORKAROUND_AVAILABLE'
    | 'PLANNED'
    | 'IN_PROGRESS'
    | 'FIXED'
    | 'CLOSED';
  isPublic?: boolean | null;
  isPinned?: boolean | null;
  /**
   * Shown publicly when status is Needs More Info.
   */
  needsMoreInfoText?: string | null;
  /**
   * Shown publicly when status is Workaround Available.
   */
  workaroundText?: string | null;
  /**
   * The update that shipped it. Its page lists this item under "From your feedback".
   */
  fixedInPatchNote?: (number | null) | PatchNote;
  upvoteCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issue-reports".
 */
export interface IssueReport {
  id: number;
  tenant?: (number | null) | Tenant;
  gameProject: number | GameProject;
  title: string;
  description: string;
  type: 'BUG' | 'IDEA';
  category:
    | 'INFORMATION'
    | 'PATCH_NOTES'
    | 'GAMEPLAY'
    | 'CRASHES'
    | 'USER_INTERFACE'
    | 'AUDIO'
    | 'VISUAL'
    | 'QUESTS'
    | 'PERFORMANCE'
    | 'OTHER';
  /**
   * Flagged submissions wait here even when review is off.
   */
  status: 'NEW' | 'PUBLISHED' | 'LINKED' | 'DISMISSED';
  issue?: (number | null) | Issue;
  submitterEmail?: string | null;
  /**
   * e.g. Windows, Steam Deck, PS5
   */
  platform?: string | null;
  gameVersion?: string | null;
  flagged?: boolean | null;
  /**
   * Why the content filter held this submission, one reason per line.
   */
  flagReasons?: string | null;
  discord?: {
    userId?: string | null;
    username?: string | null;
    messageUrl?: string | null;
    interactionId?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issue-votes".
 */
export interface IssueVote {
  id: number;
  tenant?: (number | null) | Tenant;
  issue: number | Issue;
  browserTokenHash: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abuse-reports".
 */
export interface AbuseReport {
  id: number;
  pageUrl: string;
  gameProject?: (number | null) | GameProject;
  reason: 'spam' | 'scam' | 'offensive' | 'impersonation' | 'other';
  details?: string | null;
  reporterEmail?: string | null;
  status: 'open' | 'resolved' | 'dismissed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discord-posts".
 */
export interface DiscordPost {
  id: number;
  gameProject: number | GameProject;
  patchNote?: (number | null) | PatchNote;
  issue?: (number | null) | Issue;
  stage?: ('planned' | 'in-progress' | 'shipped') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'email-contact-form' | 'discord-webhook' | 'discord-update-post' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'email-contact-form' | 'discord-webhook' | 'discord-update-post' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'game-projects';
        value: number | GameProject;
      } | null)
    | ({
        relationTo: 'patch-notes';
        value: number | PatchNote;
      } | null)
    | ({
        relationTo: 'issues';
        value: number | Issue;
      } | null)
    | ({
        relationTo: 'issue-reports';
        value: number | IssueReport;
      } | null)
    | ({
        relationTo: 'issue-votes';
        value: number | IssueVote;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'abuse-reports';
        value: number | AbuseReport;
      } | null)
    | ({
        relationTo: 'discord-posts';
        value: number | DiscordPost;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  suspended?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-projects_select".
 */
export interface GameProjectsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  logo?: T;
  banner?: T;
  theme?:
    | T
    | {
        colors?:
          | T
          | {
              background?: T;
              foreground?: T;
              mutedForeground?: T;
              surface?: T;
              accent?: T;
              accentForeground?: T;
              border?: T;
              success?: T;
              warning?: T;
              error?: T;
            };
        typography?: T;
        shape?: T;
        density?: T;
        motion?: T;
      };
  links?:
    | T
    | {
        website?: T;
        steam?: T;
        epic?: T;
        itch?: T;
        discord?: T;
        support?: T;
        docs?: T;
        merch?: T;
        playstation?: T;
        xbox?: T;
        nintendo?: T;
        gog?: T;
        youtube?: T;
        pressKit?: T;
        privacy?: T;
        terms?: T;
      };
  availability?:
    | T
    | {
        releaseState?: T;
        releaseDate?: T;
        currentVersion?: T;
        platforms?:
          | T
          | {
              platform?: T;
              storeUrl?: T;
              label?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        target?: T;
        email?: T;
        discordWebhookUrl?: T;
        externalUrl?: T;
        tallyUrl?: T;
        tallyDisplay?: T;
      };
  reportForm?:
    | T
    | {
        provider?: T;
        tallyUrl?: T;
        tallyDisplay?: T;
        externalUrl?: T;
        acceptIdeas?: T;
        reviewSubmissions?: T;
      };
  customDomain?: T;
  customDomainVerified?: T;
  discord?:
    | T
    | {
        guildId?: T;
        channelId?: T;
        webhookUrl?: T;
      };
  flagged?: T;
  flagReasons?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patch-notes_select".
 */
export interface PatchNotesSelect<T extends boolean = true> {
  tenant?: T;
  gameProject?: T;
  title?: T;
  generateSlug?: T;
  slug?: T;
  versionLabel?: T;
  summary?: T;
  content?: T;
  publishedAt?: T;
  flagged?: T;
  flagReasons?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issues_select".
 */
export interface IssuesSelect<T extends boolean = true> {
  _order?: T;
  tenant?: T;
  gameProject?: T;
  title?: T;
  generateSlug?: T;
  slug?: T;
  summary?: T;
  details?: T;
  type?: T;
  category?: T;
  status?: T;
  isPublic?: T;
  isPinned?: T;
  needsMoreInfoText?: T;
  workaroundText?: T;
  fixedInPatchNote?: T;
  upvoteCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issue-reports_select".
 */
export interface IssueReportsSelect<T extends boolean = true> {
  tenant?: T;
  gameProject?: T;
  title?: T;
  description?: T;
  type?: T;
  category?: T;
  status?: T;
  issue?: T;
  submitterEmail?: T;
  platform?: T;
  gameVersion?: T;
  flagged?: T;
  flagReasons?: T;
  discord?:
    | T
    | {
        userId?: T;
        username?: T;
        messageUrl?: T;
        interactionId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issue-votes_select".
 */
export interface IssueVotesSelect<T extends boolean = true> {
  tenant?: T;
  issue?: T;
  browserTokenHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abuse-reports_select".
 */
export interface AbuseReportsSelect<T extends boolean = true> {
  pageUrl?: T;
  gameProject?: T;
  reason?: T;
  details?: T;
  reporterEmail?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discord-posts_select".
 */
export interface DiscordPostsSelect<T extends boolean = true> {
  gameProject?: T;
  patchNote?: T;
  issue?: T;
  stage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskEmail-contact-form".
 */
export interface TaskEmailContactForm {
  input: {
    projectID: string;
    gameSlug: string;
    name?: string | null;
    email?: string | null;
    subject?: string | null;
    message: string;
  };
  output: {
    sent: boolean;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDiscord-webhook".
 */
export interface TaskDiscordWebhook {
  input: {
    projectID: string;
    gameSlug: string;
    name?: string | null;
    email?: string | null;
    subject?: string | null;
    message: string;
  };
  output: {
    sent: boolean;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDiscord-update-post".
 */
export interface TaskDiscordUpdatePost {
  input: {
    patchNoteID: number;
  };
  output: {
    posted: boolean;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}